import fs from "node:fs/promises";
import path from "node:path";

const ROOT = path.resolve(process.cwd());
const RUNS_DIR = path.join(ROOT, "runs");
const PUBLIC_DIR = path.join(ROOT, "public");

const SOURCES = [
  {
    id: "moltbook",
    kind: "web",
    url: "https://www.moltbook.com/m",
  },
  {
    id: "x_moondev",
    kind: "web",
    url: "https://x.com/moondev",
    note: "May require browser session / cookies; we still snapshot the HTML fetch result.",
  },
  {
    id: "awesome-openclaw-skills",
    kind: "web",
    url: "https://github.com/VoltAgent/awesome-openclaw-skills",
    note: "Skills collection repo (source of automation building blocks)",
  },
  {
    id: "pumpmolt",
    kind: "web",
    url: "https://github.com/PlaydaDev/pumpmolt",
    note: "Trading ideas / scripts repo",
  },
  {
    id: "bankrbot-openclaw-skills",
    kind: "web",
    url: "https://github.com/BankrBot/openclaw-skills",
    note: "Additional OpenClaw skills repo (scan for useful automation building blocks)",
  },
];

function isoDate(d = new Date()) {
  return d.toISOString().slice(0, 10);
}

function extractLinks(html, max = 200) {
  const links = [];
  const re = /href\s*=\s*"([^"]+)"/gi;
  let m;
  while ((m = re.exec(html))) {
    const href = m[1];
    if (!href) continue;
    if (href.startsWith("javascript:")) continue;
    links.push(href);
    if (links.length >= max) break;
  }
  // de-dupe
  return [...new Set(links)];
}

async function fetchText(url) {
  const res = await fetch(url, {
    headers: {
      "user-agent": "molt-scout/0.1 (+local dashboard)",
      accept: "text/html,application/json;q=0.9,*/*;q=0.8",
    },
  });
  const text = await res.text();
  return { ok: res.ok, status: res.status, text };
}

async function writeDashboard(latestRun) {
  const html = `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>MOLT Scout</title>
  <style>
    body{font-family:ui-sans-serif,system-ui,Segoe UI,Roboto,Helvetica,Arial;max-width:980px;margin:40px auto;padding:0 16px;}
    code{background:#f5f5f5;padding:2px 6px;border-radius:6px;}
    .card{border:1px solid #e5e5e5;border-radius:12px;padding:16px;margin:12px 0;}
    a{color:#0b5fff;text-decoration:none}
    a:hover{text-decoration:underline}
    .muted{color:#666}
    ul{margin:8px 0 0 18px}
  </style>
</head>
<body>
  <h1>MOLT Scout</h1>
  <p class="muted">Local dashboard generated by a daily scan. Last run: <code>${latestRun.date}</code> (${new Date(latestRun.generatedAt).toLocaleString()})</p>

  <div class="card">
    <h2>Shortlist (heuristic)</h2>
    <p class="muted">Currently basic: flags links mentioning molt/MOLT and communities (telegram/discord/reddit). We'll improve scoring as we learn what converts.</p>
    <ul>
      ${latestRun.shortlist
        .slice(0, 50)
        .map((x) => `<li><a href="${x}" target="_blank" rel="noreferrer">${x}</a></li>`)
        .join("\n")}
    </ul>
  </div>

  ${latestRun.sources
    .map(
      (s) => `
      <div class="card">
        <h2>${s.id}</h2>
        <div class="muted">${s.url} · status ${s.status} · bytes ${s.bytes}</div>
        <details style="margin-top:10px">
          <summary>Top links (${s.links.length})</summary>
          <ul>
            ${s.links
              .slice(0, 80)
              .map((l) => `<li><a href="${l}" target="_blank" rel="noreferrer">${l}</a></li>`)
              .join("\n")}
          </ul>
        </details>
      </div>
    `,
    )
    .join("\n")}

  <hr />
  <p class="muted">Data file: <a href="./latest.json">latest.json</a></p>
</body>
</html>`;

  await fs.mkdir(PUBLIC_DIR, { recursive: true });
  await fs.writeFile(path.join(PUBLIC_DIR, "index.html"), html, "utf8");
  await fs.writeFile(path.join(PUBLIC_DIR, "latest.json"), JSON.stringify(latestRun, null, 2), "utf8");
}

function buildShortlist(allLinks) {
  const norm = (u) => u.toLowerCase();
  const interesting = allLinks.filter((u) => {
    const x = norm(u);
    const community = x.includes("t.me") || x.includes("telegram") || x.includes("discord") || x.includes("reddit") || x.includes("guild") || x.includes("forum");
    const molt = x.includes("molt") || x.includes("moltbook");
    const money = x.includes("trade") || x.includes("alpha") || x.includes("profit") || x.includes("airdrop") || x.includes("launch") || x.includes("token");
    return molt && (community || money);
  });
  return [...new Set(interesting)].slice(0, 200);
}

async function main() {
  const date = isoDate();
  const generatedAt = new Date().toISOString();

  await fs.mkdir(RUNS_DIR, { recursive: true });

  const sourcesOut = [];
  const allLinks = [];

  for (const src of SOURCES) {
    let status = 0;
    let ok = false;
    let text = "";
    try {
      const r = await fetchText(src.url);
      status = r.status;
      ok = r.ok;
      text = r.text;
    } catch (e) {
      status = 0;
      ok = false;
      text = String(e);
    }

    const links = src.kind === "web" ? extractLinks(text) : [];

    // Make links absolute-ish for relative ones
    const abs = links.map((l) => {
      try {
        return new URL(l, src.url).toString();
      } catch {
        return l;
      }
    });

    allLinks.push(...abs);

    sourcesOut.push({
      id: src.id,
      url: src.url,
      ok,
      status,
      bytes: text.length,
      links: abs,
      note: src.note,
    });

    // Save raw snapshot for audit
    const safeId = src.id.replace(/[^a-z0-9_-]/gi, "_");
    await fs.writeFile(path.join(RUNS_DIR, `${date}.${safeId}.raw.txt`), text, "utf8");
  }

  const shortlist = buildShortlist(allLinks);

  const run = {
    date,
    generatedAt,
    sources: sourcesOut,
    shortlist,
  };

  const outPath = path.join(RUNS_DIR, `${date}.json`);
  await fs.writeFile(outPath, JSON.stringify(run, null, 2), "utf8");

  await writeDashboard(run);

  console.log(`MOLT scout run complete: ${outPath}`);
  console.log(`Dashboard: ${path.join(PUBLIC_DIR, "index.html")}`);
}

await main();
